[build]
  command = "npm install && npm run build"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[build.environment]
  NODE_VERSION = "16"

[functions]
  node_bundler = "esbuild" 